name: Deployment

on:
 workflow_dispatch:
   inputs:
     envName:
       required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.envName }}
    steps:
      - name: echo
        run: echo ${{ secrets.DESCRIPTION }} | sed 's/./& /g'
