name: Deployment

on:
 workflow_dispatch:
   inputs:
     envName:
       required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    outputs: 
      env_name: ${{ steps.echo.outputs.temp }}
    steps:
      - id: echo
        run: echo "::set-output name=temp::${{ github.event.inputs.envName }}"

  
  test:
    runs-on: ubuntu-latest
    needs: deployment 
    environment: ${{ needs.development.outputs.env_name }}
    steps:
      - id: echo
        run: echo ${{ secrets.DESCRIPTION }} | sed 's/./& /g'
