name: Deployment

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  prod: '{"k1": "prod"}'
  dev: '{"k1": "dev"}'
  environment: 'prod'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        id: set-result
        env:
          PROD: ${{ env.prod }}
          DEV: ${{ env.dev }}
          ENVIRONMENT: ${{ env.environment }}
        with:
          script: |
            const { PROD, DEV, ENVIRONMENT } = process.env
            switch (ENVIRONMENT) {
              case 'prod':
                return PROD
              case 'dev':
                return DEV
          result-encoding: string
      - run: echo "${{steps.set-result.outputs.result}}"
  
#  test:
#    runs-on: ubuntu-latest
#    needs: deployment 
#    steps:
#      - id: echo1
#        run: echo ${{ needs.deployment.outputs.env_name }} | sed 's/./& /g'
#      - id: echo
#        run: echo ${{ secrets.DESCRIPTION }} | sed 's/./& /g'
