name: Deployment

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  prod: '{"k1": "prod", "k2": 1}'
  dev: '{"k1": "dev", "k2": 2}'
  stage: '{"k1": "stage", "k2": 3}'

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: set-result
        env:
          PROD: ${{ env.prod }}
          DEV: ${{ env.dev }}
          STAGE: ${{ env.stage }}
          GITHUB_REF: ${{ github.ref }}
        with:
          script: |
            const { PROD, DEV, STAGE, GITHUB_REF } = process.env
            if (GITHUB_REF === 'refs/heads/main') {
                const temp = JSON.parse(DEV)
                return {...temp, ...{"k3": 5}}
            } else if (GITHUB_REF.startsWith('refs/tags/v')) {
                return PROD
            } else {
              return STAGE
            }
          result-encoding: string
      - run: echo "${{steps.set-result.outputs.result}}"
  
#  test:
#    runs-on: ubuntu-latest
#    needs: deployment 
#    steps:
#      - id: echo1
#        run: echo ${{ needs.deployment.outputs.env_name }} | sed 's/./& /g'
#      - id: echo
#        run: echo ${{ secrets.DESCRIPTION }} | sed 's/./& /g'
