name: Deployment

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  deployment:
    runs-on: ubuntu-latest
    outputs: 
      env_name: ${{ steps.echo.outputs.temp }}
    steps:
      - id: echo
        run: echo "::set-output name=temp::${{ github.event.inputs.envName }}"
      - id: main
        run: echo "::set-output name=temp::main"
        if: github.ref == 'refs/heads/main'
      - id: tag
        run: echo "::set-output name=temp::tag"
        if: startsWith(github.ref, 'refs/tags/v')
  
  test:
    runs-on: ubuntu-latest
    needs: deployment 
    environment: ${{ needs.deployment.outputs.env_name }}
    steps:
      - id: echo1
        run: echo ${{ needs.deployment.outputs.env_name }} | sed 's/./& /g'
      - id: echo
        run: echo ${{ secrets.DESCRIPTION }} | sed 's/./& /g'
