name: Deployment

on:
 workflow_dispatch:
   inputs:
     envName:
       required: true

env:
  env1:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: echo
        run: echo ${GITHUB_REF}
