---
name: Deployment

"on":
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      #- id: set-output
      #  run: |
      #    echo "test"
      - name: run hello action
        uses: ./.github/actions/hello-world-docker-action
        with:
          who-to-greet: 'Mona the Octocat'

